# Generated by Django 6.0.5 on 2026-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_wordset_word_word_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
