# Generated by Django 6.0.5 on 2026-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_wordset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='icon',
            field=models.CharField(default='bi-journal-bookmark', max_length=50),
        ),
    ]
