# Generated by Django 6.0.5 on 2026-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_wordset_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='icon_color',
            field=models.CharField(default='stat-green', max_length=30),
        ),
    ]
