# Generated by Django 6.0.5 on 2026-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
