# Generated by Django 6.0.5 on 2026-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_wordset_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
