# Generated by Django 6.0.5 on 2026-07-07 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_wordset_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
