# Generated by Django 6.0.5 on 2026-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_wordset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='description',
            field=models.CharField(default='Opis zestawu', max_length=100),
            preserve_default=False,
        ),
    ]
