# Generated by Django 6.0.5 on 2026-07-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_wordset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='level',
            field=models.CharField(default='A1', max_length=10),
            preserve_default=False,
        ),
    ]
