# Generated by Django 6.0.5 on 2026-07-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_wordset_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='image',
            field=models.CharField(default='default.png', max_length=30),
            preserve_default=False,
        ),
    ]
