# Generated by Django 6.0.5 on 2026-07-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_wordset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
