# Generated by Django 6.0.5 on 2026-09-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_wordset_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='is_shareable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordset',
            name='share_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
