# Generated by Django 6.0.5 on 2026-09-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0015_wordset_is_shareable_wordset_share_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordset',
            name='is_shareable',
        ),
        migrations.AddField(
            model_name='wordset',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
